/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_overrun_java3DGameLearning_natives_HelloWorld */

#ifndef _Included_io_github_overrun_java3DGameLearning_natives_HelloWorld
#define _Included_io_github_overrun_java3DGameLearning_natives_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_overrun_java3DGameLearning_natives_HelloWorld
 * Method:    printHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_overrun_java3DGameLearning_natives_HelloWorld_printHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
