/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_overrun_java3DGameLearning_natives_Random */

#ifndef _Included_io_github_overrun_java3DGameLearning_natives_Random
#define _Included_io_github_overrun_java3DGameLearning_natives_Random
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_overrun_java3DGameLearning_natives_Random
 * Method:    random
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_github_overrun_java3DGameLearning_natives_Random_random
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
