/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_overrun_java3DGameLearning_natives_WindowHandle */

#ifndef _Included_io_github_overrun_java3DGameLearning_natives_WindowHandle
#define _Included_io_github_overrun_java3DGameLearning_natives_WindowHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_overrun_java3DGameLearning_natives_WindowHandle
 * Method:    createWindow
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_overrun_java3DGameLearning_natives_WindowHandle_createWindow
  (JNIEnv *, jobject, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
